services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=studDB'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3305:3306'

  app:
    image: myappimage:1.0.0
    ports:
      - '8080:8080'
    environment:
      spring.datasource.url: jdbc:mysql://mysql:3306/studDB
      spring.datasource.driverClassName: com.mysql.cj.jdbc.Driver
      spring.datasource.username: myuser
      spring.datasource.password: secret
    depends_on:
      - mysql
    networks:
      - default
#volumes:
#  todo-mysql-data: